# https://developers.google.com/appengine/docs/python/config/appconfig

application: mos3abofsite
version: pelican
runtime: python27
api_version: 1
threadsafe: true


handlers:

  - url: /\d+/\d+/[^\d][^/]+/?
    script: dynamic.legacy_redirect.app

  - url: /(favicon\.ico|robots\.txt)
    static_files: output/static/misc/\1
    upload: output/static/misc/(favicon\.ico|robots\.txt)

  - url: /
    static_files: output/index.html
    upload: output/index\.html

  - url: /theme/css/.*\.ttf
    static_files: output/theme/css/\1
    upload: output/static/misc/.*\.ttf
    mime_type: application/x-font-ttf

  - url: /
    static_dir: output
