pygmentsUseClasses = true

baseURL = "https://mosab.co.uk/"
# baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Mosab Ibrahim"
theme = "rfc"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  # [[menu.main]]
  #   name = "Blog"
  #   url = "/posts/"
  #   weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 5
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 6
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 9
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
