version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # install git
      # - run: apk update && apk add git

      # checkout the repository
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ./
      - run:
          name: "Test Website"
          command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy
      - deploy:
          name: deploy to host
          steps:
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              make rsync_upload
            else
              echo "Not master branch, dry run only"
            fi
