version: 2.1

executors:
  pelican-executor:
    docker:
      - image: circleci/python:3.7.2

commands:
  install-pelican:
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

jobs:
  build:
    executor: pelican-executor
    working_directory: ~/repo
    steps:
      - install-pelican
      - run:
          name: "Build Site"
          command: |
            . venv/bin/activate
            make publish
      - run:
          name: "Add keybase.txt"
          command: |
            cp keybase.txt ~/repo/output/
      - run:
          name: "Setup .htaccess"
          command: |
            cp .htaccess ~/repo/output/
      - store_artifacts:
          path: output
          destination: output

  deploy:
    executor: pelican-executor
    working_directory: ~/repo
    steps:
      - install-pelican
      - add_ssh_keys:
          fingerprints:
            - "95:73:53:f7:ec:77:ea:19:08:53:e9:d2:ea:2a:37:d4"
      - run:
          name: "Install rsync"
          command: |
            sudo apt-get install -y rsync
      - run:
          name: "Add Host Fingerprints"
          command: |
            echo "$known_hosts" > ~/.ssh/known_hosts
      - run:
          name: "Publish Site"
          command: |
            . venv/bin/activate
            make rsync_upload
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches: {only: master}
